Update paritychecktuning.txt
unraid/lang-de_DE pull request #56
Opened 2021-03-02 10:11 UTC by SkyBird1980

some additions

2021-03-02 18:10 UTC, spencerjunraid commented
Danke. Will review and merge...

2021-03-03 13:36 UTC, ich777 requested changes

2021-03-03 13:36 UTC, ich777 commented on Parity Check Tuning/paritychecktuning.txt
> +Unscheduled array operation in progress=Bearbeite ungeplante Array Tätigkeit
Ungeplanter Array Vorgang wird ausgeführt

2021-03-03 13:36 UTC, ich777 commented on Parity Check Tuning/paritychecktuning.txt
> +No array operation currently in progress=Zur Zeit keine Array Tätigkeit
Es wird kein Array Vorgang ausgeführt

2021-03-03 13:36 UTC, ich777 commented on Parity Check Tuning/paritychecktuning.txt
> +already running=Wird schon ausgeführt
wird bereits ausgeführt

2021-03-03 13:36 UTC, ich777 commented on Parity Check Tuning/paritychecktuning.txt
> +ParityRead-Check History=Parity/Read-Check History=Bisherige Parity-Prüfungen
Bisherige Paritäts Prüfungen
@spencerjunraid is in this line something wrong? I think the english text is doubled?

2021-03-03 13:36 UTC, ich777 commented on Parity Check Tuning/paritychecktuning.txt
> +Click to show parity-check history=Klicken um die bisherigen Parity-Prüfungen zu sehen
Klicke um Paritätsprüfungs Verlauf anzuzeigen

2021-03-03 13:36 UTC, ich777 commented on Parity Check Tuning/paritychecktuning.txt
> +unknown action %s=Unbekannte action: %s
unbekannte Aktion %s

2021-03-03 13:36 UTC, ich777 commented on Parity Check Tuning/paritychecktuning.txt
> +Correcting Parity Check=Parity Prüfung mit Fehlerverbesserung
Paritätsprüfung mit Fehlerkorrektur

2021-03-03 13:36 UTC, ich777 commented on Parity Check Tuning/paritychecktuning.txt
> +NonCorrecting Parity Check=Parity Prüfung ohne Fehlerverbesserung
Paritätsprüfung ohne Fehlerkorrektur

2021-03-03 13:36 UTC, ich777 commented on Parity Check Tuning/paritychecktuning.txt
> +No action specified=Keine Aktion spezifiziert
Keine Aktion angegeben

2021-03-03 13:36 UTC, ich777 commented on Parity Check Tuning/paritychecktuning.txt
> +No cron events for this plugin are needed=Für dieses Plugin werden keine Cron Events gebraucht
Für dieses Plugin werden keine Cron Einträge gebraucht

2021-03-03 13:36 UTC, ich777 commented on Parity Check Tuning/paritychecktuning.txt
> +created cron entries for running increments=Nötige Cron Einträge würden hinzugefügt
erforderliche Cron Einträge für die Ausführung wurden hinzugefügt

2021-03-03 13:36 UTC, ich777 commented on Parity Check Tuning/paritychecktuning.txt
> +created cron entry for monitoring disk temperatures= Cron Eintrag zur Überwachung der Festplattentemperaturen wurde hinzugefügt
Cron Eintrag zur Überwachung der Datenträgertemperaturen wurde hinzugefügt

2021-03-03 13:36 UTC, ich777 commented on Parity Check Tuning/paritychecktuning.txt
> +Array operation paused but not for temperature related reason=Array Operation pausiert - nicht temperaturabhäng
Array Vorgang pausiert - nicht aus temperaturbedingten Gründen

2021-03-03 13:36 UTC, ich777 commented on Parity Check Tuning/paritychecktuning.txt
> +to resume %s=um weiter zu machen %s
zum Fortsetzen %s

2021-03-03 13:36 UTC, ich777 commented on Parity Check Tuning/paritychecktuning.txt
> +option not currently recognised=Option wurde nicht erkannt
Vorgang wurde nicht erkannt

2021-03-03 13:36 UTC, ich777 commented on Parity Check Tuning/paritychecktuning.txt
> +Parity check appears to be paused=Parity Check scheint zu pausieren
Paritätsüberprüfung scheint pausiert zu sein

2021-03-07 22:36 UTC, ich777 commented
@SkyBird1980 was sagst du zu den Vorschlägen?

2021-03-08 03:43 UTC, SkyBird1980 commented
Ja. Ist ok für mich. 
Manchmal schwer mit Übersetzungen - gerade wenn es der Kontext ist der die richtige Übersetzung erst möglich macht.
Man arbeitet ja  zusammen. Daher viele Meinungen.

2021-03-08 04:56 UTC, ich777 commented
Kannst du die änderungen in deinem Github Repo übernehemen da nur du sie ändern kannst und der PR hier dementsprechend aktualisiert wird.

2021-03-08 14:01 UTC, SkyBird1980 commented
Ich hoffe ich hab jetzt nichts übersehen..

2021-03-08 16:39 UTC, ich777 requested changes
Nur ein paar Kleinigkeiten, versuch das nur bestmöglich an die bestehenden Übersetzungen anzupassen... :)

2021-03-08 16:39 UTC, ich777 commented on Parity Check Tuning/paritychecktuning.txt
>  unknown action %s=Unbekannte action: %s
@SkyBird1980 Hier stimmt "action" nicht und Unbekannte würd ich klein schreiben da noch was vorangestellt wird in dem Kontext.

2021-03-08 16:39 UTC, ich777 commented on Parity Check Tuning/paritychecktuning.txt
> +No action specified=Keine Aktion spezifiziert
Was sagst du zu "gewählt" statt "spezifiziert"?

2021-03-08 16:39 UTC, ich777 commented on Parity Check Tuning/paritychecktuning.txt
> +No cron events for this plugin are needed=Für dieses Plugin werden keine Cron Events gebraucht
Hier bitte auch "Events" übersetzen.

2021-03-08 16:39 UTC, ich777 commented on Parity Check Tuning/paritychecktuning.txt
> +created cron entries for running increments=Nötige Cron Einträge würden hinzugefügt
Was sagst zu meine vorhergehenden Vorschlag?

2021-03-08 17:17 UTC, SkyBird1980 commented
Ich push gleich nochmal :) Bin nicht so ganz firm mit Github. Gut das hier noch mehr Augen drüber schauen.

2021-03-08 18:32 UTC, ich777 requested changes

2021-03-08 18:32 UTC, ich777 commented on Parity Check Tuning/paritychecktuning.txt
> +%s appears to be a regular scheduled check=%s ist eine geplante Prüfung
%s scheint eine geplante Prüfung zu sein

2021-03-08 18:32 UTC, ich777 commented on Parity Check Tuning/paritychecktuning.txt
> +No cron events for this plugin are needed=Für dieses Plugin werden keine Cron Einträge gebraucht
statt "gebraucht" bitte "benötigt"

2021-03-08 18:32 UTC, ich777 commented
Sorry hab noch was gefunden und dann sollte es aber passen ;)

2021-03-11 07:01 UTC, ich777 commented
@spencerjunraid can be merged.

2021-03-11 18:01 UTC, merged