Translations
unraid/lang-de_DE pull request #65
Opened 2021-05-22 07:09 UTC by SkyBird1980

Translated up to Line 117

2021-05-22 07:57 UTC, ich777 requested changes
Bitte wieder die Vorschläge ansehen.

2021-05-22 07:57 UTC, ich777 commented on dashboard.txt
> +%s ago=% vorher
@SkyBird1980 hier fehlt das "s" nach dem "%".

2021-05-22 07:57 UTC, ich777 commented on dashboard.txt
> +SMART health-check failed=SMART Gesundheitsüberprüfung fehlgeschlagen
@SkyBird1980 ich würde hier sagen das sich "SMART Health-Check fehlgeschlagen" nach besser anhört.
Eine Festplatte kann streng genommen nicht "Gesund" sein... Für manche Begriffe gibt es eben keinen richtigen Deutschen Begriff. @vakilando was würdest du hierzu sagen?

2021-05-22 07:57 UTC, ich777 commented on dashboard.txt
> +Click to toggle CPU chart=Klicken um die CPU Anzeige umzuschalten
In welchem Kontext steht das?

2021-05-22 07:57 UTC, ich777 commented on dashboard.txt
> +Network traffic=Netzwerk Verkehr
@SkyBird1980 "Auslasung" oder "Netzwerktraffic", wort wörtlich würde es Netzwerk Verkehr heißen was sagst du hierzu @vakilando ?

2021-05-26 15:00 UTC, ich777 commented
@spencerjunraid can be merged.

2021-05-26 17:35 UTC, spencerjunraid commented
sehr gut!

2021-05-26 17:35 UTC, merged